### ISSUE TITLE
TypeError: _get_local_path() got an unexpected keyword argument 'force'

### ISSUE THREAD

**Issue by zhangnan-hust** [facebookresearch/unbiased-teacher#9]
Traceback (most recent call last):
  File "/home/zhangkai/zhangnan/semi-supervised/unbiased-teacher-main/train_net.py", line 80, in <module>
    args=(args,),
  File "/home/zhangkai/anaconda3/envs/detectron2/lib/python3.6/site-packages/detectron2/engine/launch.py", line 62, in launch
    main_func(*args)
  File "/home/zhangkai/zhangnan/semi-supervised/unbiased-teacher-main/train_net.py", line 63, in main
    trainer.resume_or_load(resume=args.resume)
  File "/home/zhangkai/anaconda3/envs/detectron2/lib/python3.6/site-packages/detectron2/engine/defaults.py", line 353, in resume_or_load
    checkpoint = self.checkpointer.resume_or_load(self.cfg.MODEL.WEIGHTS, resume=resume)
  File "/home/zhangkai/anaconda3/envs/detectron2/lib/python3.6/site-packages/fvcore/common/checkpoint.py", line 215, in resume_or_load
    return self.load(path, checkpointables=[])
  File "/home/zhangkai/anaconda3/envs/detectron2/lib/python3.6/site-packages/fvcore/common/checkpoint.py", line 140, in load
    path = self.path_manager.get_local_path(path)
  File "/home/zhangkai/anaconda3/envs/detectron2/lib/python3.6/site-packages/iopath/common/file_io.py", line 1100, in get_local_path
    path, force=force, **kwargs
TypeError: _get_local_path() got an unexpected keyword argument 'force'

Process finished with exit code 1

----------------------  ---------------------------------------------------------------------------------------
sys.platform            linux
Python                  3.6.13 |Anaconda, Inc.| (default, Feb 23 2021, 21:15:04) [GCC 7.3.0]
numpy                   1.19.2
detectron2              0.4 @/home/zhangkai/anaconda3/envs/detectron2/lib/python3.6/site-packages/detectron2
Compiler                GCC 7.3
CUDA compiler           CUDA 10.1
detectron2 arch flags   3.7, 5.0, 5.2, 6.0, 6.1, 7.0, 7.5
DETECTRON2_ENV_MODULE   <not set>
PyTorch                 1.8.1 @/home/zhangkai/anaconda3/envs/detectron2/lib/python3.6/site-packages/torch
PyTorch debug build     False
GPU available           True
GPU 0                   GeForce GTX 1080 (arch=6.1)
GPU 1                   Quadro M4000 (arch=5.2)
CUDA_HOME               /usr/local/cuda-10.0
Pillow                  8.2.0
torchvision             0.9.1 @/home/zhangkai/anaconda3/envs/detectron2/lib/python3.6/site-packages/torchvision
torchvision arch flags  3.5, 5.0, 6.0, 7.0, 7.5
fvcore                  0.1.3.post20210317
cv2                     4.5.1
----------------------  ---------------------------------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.7.0 (Git Hash 7aed236906b1f7a05c0917e5257a1af05e9ff683)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=10.2, CUDNN_VERSION=7.6.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.8.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

I create the environment and run the code by readme but get this error. What is the problem?

**Comment by xiaohui0225** [comment]
您好，我也在尝试实现这个项目，希望可以和您共同讨论，VX：zh2236358555
